### ISSUE TITLE
hardware

### ISSUE THREAD

**Issue by hdzhang-code** [iliaschalkidis/lmtc-emnlp2020#1]
Thanks for the work. I have learned good stuff from the paper.

Could I know on what hardware are the model trained?

**Comment by iliaschalkidis** [comment]
Thanks for your kind words.

There were various GPU server setups. At the time of the experiments, I can't recall anything more than a single 11GB GPU card (GTX1080Ti, RTX2080Ti) for training a single model.

**Comment by hdzhang-code** [comment]
Thanks for the feedback.

I have never touched NLP with long documents and so many labels. I'm just worrying about the hardware that is able to handle so many data. GTX1080Ti or RTX2080Ti are good news for me.
